"""Enterprise configuration engine for ITcopilot."""

from common.config.constants import (
    DEFAULT_API_VERSION,
    DEFAULT_APP_NAME,
    DEFAULT_APP_VERSION,
    DEFAULT_BUILD_NUMBER,
    DEFAULT_JWT_ALGORITHM,
    DEFAULT_RELEASE_DATE,
    ENV_FILES,
    INSECURE_SECRET_KEYS,
    PROJECT_ROOT,
    SUPPORTED_ASSESSMENT_YEARS,
    SUPPORTED_LOG_LEVELS,
)
from common.config.exceptions import ConfigurationError
from common.config.feature_flags import FeatureFlags
from common.config.logging import configure_logging, get_logger
from common.config.metadata import ApplicationMetadata, get_application_metadata
from common.config.settings import (
    BaseAppSettings,
    DevelopmentSettings,
    ProductionSettings,
    Settings,
    TestingSettings,
    get_settings,
    load_settings,
    reset_settings_cache,
    resolve_settings_class,
)
from common.config.tax_config import (
    TAX_YEAR_CONFIGURATIONS,
    CapitalGainRates,
    FifoConfiguration,
    GrandfatheringRules,
    Section80Limits,
    TaxYearConfiguration,
    get_default_tax_config,
    get_tax_year_config,
)
from common.config.types import (
    Environment,
    LogLevel,
    ResidentStatus,
    SurchargeThreshold,
    TaxRegime,
    TaxRegimeName,
    TaxSlabDefinition,
)
from common.config.validators import (
    validate_assessment_year,
    validate_database_url,
    validate_host,
    validate_log_level,
    validate_port,
    validate_required_variables,
    validate_tax_regime,
)

__all__ = [
    "DEFAULT_API_VERSION",
    "DEFAULT_APP_NAME",
    "DEFAULT_APP_VERSION",
    "DEFAULT_BUILD_NUMBER",
    "DEFAULT_JWT_ALGORITHM",
    "DEFAULT_RELEASE_DATE",
    "ENV_FILES",
    "INSECURE_SECRET_KEYS",
    "PROJECT_ROOT",
    "SUPPORTED_ASSESSMENT_YEARS",
    "SUPPORTED_LOG_LEVELS",
    "TAX_YEAR_CONFIGURATIONS",
    "ApplicationMetadata",
    "BaseAppSettings",
    "CapitalGainRates",
    "ConfigurationError",
    "DevelopmentSettings",
    "Environment",
    "FeatureFlags",
    "FifoConfiguration",
    "GrandfatheringRules",
    "LogLevel",
    "ProductionSettings",
    "ResidentStatus",
    "Section80Limits",
    "Settings",
    "SurchargeThreshold",
    "TaxRegime",
    "TaxRegimeName",
    "TaxSlabDefinition",
    "TaxYearConfiguration",
    "TestingSettings",
    "configure_logging",
    "get_application_metadata",
    "get_default_tax_config",
    "get_logger",
    "get_settings",
    "get_tax_year_config",
    "load_settings",
    "reset_settings_cache",
    "resolve_settings_class",
    "validate_assessment_year",
    "validate_database_url",
    "validate_host",
    "validate_log_level",
    "validate_port",
    "validate_required_variables",
    "validate_tax_regime",
]
